# @format

BOT:
  OWNERS: ["ID","ID"]
  ADMINS: ["ID","ID"]



LINKS:
  SUPPORT: "SUPPORT SERVER"
  MONGO_URI: "MONGO URL"
  VOTING: "https://top.gg/bot/1272058924547178581"

SPOTIFY:
  ID: "e7c9c292bbc24745b33743348e560d96"
  SECRET: "4726d6d6eba34cfe889c26844fcabc97"

MANAGER:
  OWNERS: ["1052620216443601076", "975254584224268298"]
  TOKEN: "MTMxMDk4ODQ2NzM2NjM5NTk1NQ.GlDHEm.1XPBmDLm4VTRgWQu-MwIRTCl1LISfXxck3_RjQ"

NEX:
  PREFIX: "%"
  EMOJIS: "black"
  COLOR: "548fc1"
  SHARDS: auto
  PER_CLUSTER: 1
  TOKEN: "MTMzNjcyODQwNTAyMTk1MDA3Ng.GIEBnn.cXKhVA_IcULb0_HkPidNmMW2kruC_mCjnf6c6I"
  VOTEURI: "https://top.gg/bot/1272058924547178581/vote"
  TOPGGAUTH: ""

JINGLE:
   PREFIX: "?"
   EMOJIS: "black"
   COLOR: "#555555"
   SHARDS: "auto"
   PER_CLUSTER: 2
   TOKEN: "MTQwNjQ0OTQxMjM5MzE0MDI3NA.GcJkq1.xb55TGVPxgCGHWAxo8N6UTgSvo5DlytU_IpUXA"
   TOPGGAUTH: ""
   VOTEURI: ""


KYOKO:
   PREFIX: "&"
   EMOJIS: "black"
   COLOR: "#548fc1"
   SHARDS: "auto"
   PER_CLUSTER: 2
   TOKEN: "MTMyMzg2NTQyODk0MjEzMTI3MQ.GsHyvP.mH9J0La4q2RGYJX7w0J3HgLEPQ5U12pmJpL2CE "
   TOPGGAUTH: ""

WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1286695127150104696/vPTOuOfNRlMiauDY7duWFo0o1JeXeVsRWVw13pbjRes74bIxAgZSyCAqDG_-tn21CW9s"
  STATIC: "https://discord.com/api/webhooks/1286695213745569874/_FmFIl88xAGlbv-8SprmQpfseBZ7P7stZE1QINEqt5agu4wvM63IeMCCssM0dXNUHZeY"
  PLAYER: "https://discord.com/api/webhooks/1286695355223900293/HUf-9vZqH4Gj_67Pq_6mDvhme5gt4MQ0lFMAMC-VMZKfCo4IMFin9MGNO82TAwcHSIAu"
  SERVER: "https://discord.com/api/webhooks/1286695421909143674/uGoc1Z5o2cdh7g5_3BGHypBA2zVuNLmG1B4D4voOW2w_3laQJDl2g3qFjXB0wa3D2FeO"
  COMMAND: "https://discord.com/api/webhooks/1286695492671115316/uysPkZPhyLWjKHw1dkrkgVzjo9FpO9crTkDyaIbBDkw6QgUV8I0BVN6VTUnubu0T_DN_"
